"""Build docs/data/network.json, the compact network used by the static trip planner in docs/.

Inputs (read only): gtfs/{routes,trips,stops,stop_times,transfers}.txt (generated by build_gtfs.py, so only
located stops and estimated or sourced stop times), data/{mode}/routes.csv for headways, and
data/rail/{route_stops,timetable}.csv for rail stop patterns and real run times.
Output: docs/data/network.json (minified, coordinates rounded to 5 decimals). Prints its size.

Modelling:
- Non-rail routes: one stop pattern per direction from the GTFS template trip (service "daily", else
  "weekdays", else the first one), cumulative ride minutes from its stop times.
- Rail: the main pattern per direction is data/rail/route_stops.csv (longest trip pattern, located stops
  only). Each hop's run time is the median over all timetable trips that call at both stops consecutively
  along that pattern. Trips calling at stations outside the main pattern (branches, through workings) add
  up to MAX_RAIL_VARIANTS extra patterns per direction, timed from their median trip.
- Headway: mean of headway_min_peak and headway_min_offpeak in data/{mode}/routes.csv. Blank for bus,
  minibus, auto: the build_gtfs defaults (15, 15, 10). Blank for rail: service span / trip count.
- Never emits interpolated coordinates: every stop is a located GTFS stop.
- Shapes (key "sh"): for metro and rail, each consecutive stop pair ("hop") of every pattern is routed
  along OpenStreetMap track geometry from sources/raw/osm_rail_ways.json (made by
  `scripts/osm_pbf_extract.py --rail-ways`): stops snap to the nearest track node of their mode's graph
  (metro: subway and light_rail; rail: rail; every node within SNAP_SLACK_M of the nearest counts,
  so either track of a double line can be used), shortest path between them (service track such as
  sidings and yards costs SERVICE_COST times its length, so it is used only to bridge gaps), simplified (Douglas-Peucker,
  SIMPLIFY_M) and stored as a Google encoded polyline under "i-j" (i < j, new stop indices, drawn i to j).
  A hop is left out (the planner draws a straight line) when a stop is over SNAP_M from track or the
  track path is more than DETOUR_MAX times the straight distance plus 1 km. Missing input file: no shapes.
- Water barriers for walking, from sources/raw/osm_water.json (made by `scripts/osm_pbf_extract.py --water`):
  "rv" the Hooghly centreline (simplified to RIVER_SIMPLIFY_M), "wc" named canals and smaller rivers at least
  CANAL_MIN_KM long (simplified to CANAL_SIMPLIFY_M), all as encoded polylines, and "wb" the points where a
  walkable OSM highway bridge crosses one of those canals ([lat, lon], merged within BRIDGE_MERGE_M). The
  planner sends walks that cross a canal over the nearest such bridge and refuses walks across the Hooghly
  except over its footway bridges. Missing input file: empty lists.

- Place search index docs/data/places.json (build_places): named places for the planner's From/To search, from
  sources/raw/osm_places_index.json (`scripts/osm_pbf_extract.py --places`, falls back to the bus gazetteer
  osm_gazetteer.json), GeoNames (geonames_IN.txt, CC BY 4.0) and Wikidata (wikidata_places.json, CC0). Each place
  gets a type label (PLACE_TYPES) and a rank (localities and big landmarks high). Same spelling key (norm_key,
  as normName in app.js) close by is merged (alt names kept, Wikidata presence raises the rank); a place whose
  name matches a transit stop close by is left out, the stop covers it. Kept: everything inside CORE_BBOX,
  outside it only places within PLACE_MAX_STOP_KM of a mapped stop. Each row names its nearest locality as an
  area hint. Rows: [name, lat, lon, type, rank, area row or -1, "alt|names"].

Usage: venv/bin/python scripts/build_web.py            (network.json, then places.json)
       venv/bin/python scripts/build_web.py --places   (places.json only, from the current network.json)
"""
from __future__ import annotations

import csv
import json
import re
import statistics
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GTFS = ROOT / "gtfs"
DATA = ROOT / "data"
OUT = ROOT / "docs" / "data" / "network.json"

MODE_COLOR = {
    "bus": "#E8590C",
    "minibus": "#B7791F",
    "metro": "#7B2CBF",
    "rail": "#1C7ED6",
    "auto": "#2B8A3E",
    "ferry": "#0B7285",
    "tram": "#C2255C",
}
DEFAULT_HEADWAY = {"bus": 15, "minibus": 15, "auto": 10}
MAX_RAIL_VARIANTS = 3
MODE_DIRS = ["bus", "metro", "rail", "auto", "ferry", "tram"]
RAIL_WAYS = ROOT / "sources" / "raw" / "osm_rail_ways.json"
SNAP_M = 800
DETOUR_MAX = 2.0
SIMPLIFY_M = 6
SERVICE_COST = 3.0
SNAP_SLACK_M = 120
WATER = ROOT / "sources" / "raw" / "osm_water.json"
RIVER_SIMPLIFY_M = 40
CANAL_SIMPLIFY_M = 10
CANAL_MIN_KM = 1.0
CANAL_SKIP = {"Ganga River"}  # a duplicate piece of the Hooghly; its road bridges have no footway
BRIDGE_MERGE_M = 40


def read(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def hms_to_min(t: str) -> float:
    h, m, s = (int(x) for x in t.split(":"))
    return h * 60 + m + s / 60


def route_mode(r: dict) -> str:
    rt, ag = r["route_type"], r["agency_id"]
    if rt == "1":
        return "metro"
    if rt == "2":
        return "rail"
    if rt == "0":
        return "tram"
    if rt == "4":
        return "ferry"
    if ag == "share_auto":
        return "auto"
    if ag == "minibus":
        return "minibus"
    return "bus"


def headways() -> dict[str, float | None]:
    out: dict[str, float | None] = {}
    for mode in MODE_DIRS:
        p = DATA / mode / "routes.csv"
        if not p.exists():
            continue
        for r in read(p):
            vals = [float(v) for v in (r["headway_min_peak"], r["headway_min_offpeak"]) if v.strip()]
            out[r["route_id"]] = round(sum(vals) / len(vals), 1) if vals else None
    return out


def main() -> None:
    stops_rows = read(GTFS / "stops.txt")
    stop_idx: dict[str, int] = {}
    stops: list[list] = []
    for s in stops_rows:
        stop_idx[s["stop_id"]] = len(stops)
        stops.append([s["stop_id"], s["stop_name"], round(float(s["stop_lat"]), 5), round(float(s["stop_lon"]), 5), []])

    routes_rows = read(GTFS / "routes.txt")
    hw = headways()
    trips = read(GTFS / "trips.txt")
    trips_by_rd: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for t in trips:
        trips_by_rd[(t["route_id"], t["direction_id"])].append(t)

    # stop_times only for non-rail template trips (rail comes from data/rail/timetable.csv)
    wanted: set[str] = set()
    chosen: dict[tuple[str, str], str] = {}
    for key, ts in trips_by_rd.items():
        if key[0].startswith("rail_"):
            continue
        pref = {"daily": 0, "weekdays": 1}
        t = sorted(ts, key=lambda x: pref.get(x["service_id"], 2))[0]
        chosen[key] = t["trip_id"]
        wanted.add(t["trip_id"])
    st_by_trip: dict[str, list[tuple[int, str, float]]] = defaultdict(list)
    with (GTFS / "stop_times.txt").open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["trip_id"] in wanted:
                st_by_trip[r["trip_id"]].append((int(r["stop_sequence"]), r["stop_id"], hms_to_min(r["departure_time"])))

    # rail inputs
    rail_main: dict[tuple[str, str], list[str]] = defaultdict(list)
    for r in sorted(read(DATA / "rail" / "route_stops.csv"), key=lambda x: (x["route_id"], x["direction"], int(x["seq"]))):
        if r["stop_id"] in stop_idx:
            rail_main[(r["route_id"], r["direction"])].append(r["stop_id"])
    rail_trips: dict[tuple[str, str, str], list[tuple[int, str, float]]] = defaultdict(list)
    for r in read(DATA / "rail" / "timetable.csv"):
        t = r["departure"] or r["arrival"]
        if not t:
            continue
        rail_trips[(r["route_id"], r["direction"], r["trip_id"])].append((int(r["seq"]), r["stop_id"], hms_to_min(t)))
    rail_by_rd: dict[tuple[str, str], list[list[tuple[str, float]]]] = defaultdict(list)
    for (rid, d, _tid), rows in rail_trips.items():
        rows.sort()
        seq: list[tuple[str, float]] = []
        prev = None
        off = 0.0
        for _, sid, m in rows:
            if prev is not None and m + off < prev - 1:
                off += 1440  # past midnight
            m += off
            prev = m
            if sid in stop_idx:
                seq.append((sid, m))
        if len(seq) >= 2:
            rail_by_rd[(rid, d)].append(seq)

    out_routes = []
    n_variants = 0
    for r in routes_rows:
        rid = r["route_id"]
        mode = route_mode(r)
        h = hw.get(rid)
        if h is None:
            h = DEFAULT_HEADWAY.get(mode)
        patterns = []  # list of (direction, [stop idx], [cum min], headway or None)
        dirs = sorted({k[1] for k in trips_by_rd if k[0] == rid})
        for d in dirs:
            if mode != "rail":
                rows = sorted(st_by_trip.get(chosen.get((rid, d), ""), []))
                if len(rows) < 2:
                    continue
                t0 = rows[0][2]
                patterns.append((d, [stop_idx[s] for _, s, _ in rows], [round(m - t0, 1) for _, _, m in rows], None))
                continue
            trips_rd = rail_by_rd.get((rid, d), [])
            main_pat = rail_main.get((rid, d), [])
            main_set = set(main_pat)
            if len(main_pat) >= 2:
                hop_times: list[list[float]] = [[] for _ in range(len(main_pat) - 1)]
                pos = {s: i for i, s in enumerate(main_pat)}
                for seq in trips_rd:
                    for (a, ta), (b, tb) in zip(seq, seq[1:]):
                        if a in pos and b in pos and pos[b] == pos[a] + 1 and tb >= ta:
                            hop_times[pos[a]].append(tb - ta)
                cum = [0.0]
                for i, ht in enumerate(hop_times):
                    if ht:
                        step = statistics.median(ht)
                    else:  # no trip calls at both: use any trip calling at both, else 40 km/h straight line x 1.2
                        a, b = main_pat[i], main_pat[i + 1]
                        spans = [dict(seq)[b] - dict(seq)[a] for seq in trips_rd if a in dict(seq) and b in dict(seq) and dict(seq)[b] > dict(seq)[a]]
                        if spans:
                            step = statistics.median(spans)
                        else:
                            sa, sb = stops[stop_idx[a]], stops[stop_idx[b]]
                            step = haversine(sa[2], sa[3], sb[2], sb[3]) * 1.2 / 40 * 60
                    cum.append(cum[-1] + max(step, 0.5))
                patterns.append((d, [stop_idx[s] for s in main_pat], [round(c, 1) for c in cum], None))
            # branch and through patterns not covered by the main pattern
            pat_count: Counter = Counter()
            pat_trips: dict[tuple, list] = defaultdict(list)
            for seq in trips_rd:
                key = tuple(s for s, _ in seq)
                if set(key) - main_set:
                    pat_count[key] += 1
                    pat_trips[key].append(seq)
            seen_sets: list[set] = []
            for key, cnt in pat_count.most_common():
                if len([p for p in patterns if p[0] == d]) > MAX_RAIL_VARIANTS:
                    break
                ks = set(key)
                if any(ks <= s for s in seen_sets):
                    continue
                seen_sets.append(ks)
                seqs = sorted(pat_trips[key], key=lambda q: q[-1][1] - q[0][1])
                med = seqs[len(seqs) // 2]
                t0 = med[0][1]
                deps = sorted(q[0][1] for q in pat_trips[key])
                vh = round(max(30.0, (deps[-1] - deps[0]) / cnt), 0) if cnt > 1 else 240.0
                patterns.append((d, [stop_idx[s] for s, _ in med], [round(m - t0, 1) for _, m in med], min(vh, 240.0)))
                n_variants += 1
            if mode == "rail" and h is None and trips_rd:
                deps = sorted(q[0][1] for q in trips_rd)
                h = round(max(20.0, (deps[-1] - deps[0]) / len(trips_rd)), 0)
        if not patterns:
            continue
        for _, sidx, _, _ in patterns:
            for i in sidx:
                if mode not in stops[i][4]:
                    stops[i][4].append(mode)
        entry = {
            "id": rid,
            "s": r["route_short_name"],
            "l": r["route_long_name"],
            "m": mode,
            "a": r["agency_id"],
            "c": MODE_COLOR[mode],
            "h": h if h is not None else 30,
            "p": [[int(d), sidx, cum] + ([vh] if vh is not None else []) for d, sidx, cum, vh in patterns],
        }
        if r.get("route_color"):
            entry["lc"] = "#" + r["route_color"]
        out_routes.append(entry)

    # keep only stops used by a pattern, then remap indices
    used = sorted({i for rt in out_routes for p in rt["p"] for i in p[1]})
    remap = {old: new for new, old in enumerate(used)}
    out_stops = [stops[i] for i in used]
    for rt in out_routes:
        for p in rt["p"]:
            p[1] = [remap[i] for i in p[1]]
    for s in out_stops:
        s[4] = "".join(sorted({m[0] if m != "minibus" else "n" for m in s[4]}))  # b bus, n minibus, m metro, r rail, a auto, f ferry, t tram
    id_to_new = {s[0]: i for i, s in enumerate(out_stops)}
    transfers = []
    for t in read(GTFS / "transfers.txt"):
        a, b = id_to_new.get(t["from_stop_id"]), id_to_new.get(t["to_stop_id"])
        if a is not None and b is not None and t.get("min_transfer_time"):
            transfers.append([a, b, round(int(t["min_transfer_time"]) / 60, 1)])

    shapes, shape_stats = build_shapes(out_routes, out_stops)

    net = {
        "meta": {
            "built": date.today().isoformat(),
            "source": "https://github.com/arkodeepg/calcutta-transport",
            "licence": "ODbL 1.0, (c) OpenStreetMap contributors and the sources in CREDITS.md",
            "stop_fields": ["id", "name", "lat", "lon", "modes"],
            "mode_letters": {"b": "bus", "n": "minibus", "m": "metro", "r": "rail", "a": "auto", "f": "ferry", "t": "tram"},
            "pattern_fields": ["direction", "stop_indices", "cumulative_ride_min", "headway_override_min (optional)"],
            "colors": MODE_COLOR,
            "water": "rv: Hooghly centreline pieces, wc: canals, as encoded polylines; wb: [lat, lon] walkable bridge crossings of the canals",
            "shapes": "sh: {'i-j': Google encoded polyline (precision 5) from stop i to stop j, i < j}, metro and rail hops along OSM track",
        },
        "stops": out_stops,
        "routes": out_routes,
        "transfers": transfers,
        "sh": shapes,
        **water_barriers(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(net, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    by_mode = Counter(r["m"] for r in out_routes)
    print(f"wrote {OUT.relative_to(ROOT)}: {OUT.stat().st_size / 1024:.1f} KiB, {len(out_stops)} stops, "
          f"{len(out_routes)} routes ({dict(by_mode)}), {sum(len(r['p']) for r in out_routes)} patterns "
          f"(rail variants {n_variants}), {len(transfers)} transfers, shapes {shape_stats}")


# ---------- metro and rail shapes from OSM track ----------
def build_shapes(out_routes: list[dict], out_stops: list[list]) -> tuple[dict[str, str], str]:
    import heapq
    if not RAIL_WAYS.exists():
        return {}, "skipped (no sources/raw/osm_rail_ways.json)"
    els = json.loads(RAIL_WAYS.read_text(encoding="utf-8"))["elements"]
    coord = {e["id"]: (e["lat"], e["lon"]) for e in els if e["type"] == "node"}
    graphs: dict[str, dict[int, list[tuple[int, float]]]] = {"metro": defaultdict(list), "rail": defaultdict(list)}
    for w in els:
        if w["type"] != "way":
            continue
        g = graphs["metro" if w["tags"].get("railway") in ("subway", "light_rail") else "rail"]
        cost = SERVICE_COST if w["tags"].get("service") else 1.0  # sidings and yards only when needed
        for a, b in zip(w["nodes"], w["nodes"][1:]):
            d = haversine(*coord[a], *coord[b]) * 1000 * cost
            g[a].append((b, d))
            g[b].append((a, d))
    # grid for snapping
    grids: dict[str, dict[tuple[int, int], list[int]]] = {}
    for m, g in graphs.items():
        gr: dict[tuple[int, int], list[int]] = defaultdict(list)
        for n in g:
            la, lo = coord[n]
            gr[(int(la * 200), int(lo * 200))].append(n)  # ~550 m cells
        grids[m] = gr

    def snap(m: str, lat: float, lon: float) -> list[int]:
        """Every track node within SNAP_SLACK_M of the nearest one, so both tracks of a double line count."""
        gr = grids[m]
        ci, cj = int(lat * 200), int(lon * 200)
        cands = []
        for i in range(ci - 2, ci + 3):
            for j in range(cj - 2, cj + 3):
                for n in gr.get((i, j), ()):
                    d = haversine(lat, lon, *coord[n]) * 1000
                    if d <= SNAP_M:
                        cands.append((d, n))
        if not cands:
            return []
        best = min(cands)[0]
        return [n for d, n in cands if d <= best + SNAP_SLACK_M]

    def path(m: str, srcs: list[int], dsts: list[int], limit: float) -> list[int] | None:
        g = graphs[m]
        targets = set(dsts)
        dist = {a: 0.0 for a in srcs}
        prev: dict[int, int] = {}
        pq = [(0.0, a) for a in srcs]
        heapq.heapify(pq)
        while pq:
            d, u = heapq.heappop(pq)
            if u in targets:
                out = [u]
                while out[-1] in prev:
                    out.append(prev[out[-1]])
                return out[::-1]
            if d > dist.get(u, 1e18) or d > limit:
                continue
            for v, w in g[u]:
                nd = d + w
                if nd < dist.get(v, 1e18):
                    dist[v] = nd
                    prev[v] = u
                    heapq.heappush(pq, (nd, v))
        return None

    shapes: dict[str, str] = {}
    failed = 0
    seen: set[tuple[int, int]] = set()
    for rt in out_routes:
        m = rt["m"]
        if m not in graphs:
            continue
        for p in rt["p"]:
            for i, j in zip(p[1], p[1][1:]):
                key = (min(i, j), max(i, j))
                if key in seen:
                    continue
                seen.add(key)
                a, b = out_stops[key[0]], out_stops[key[1]]
                straight = haversine(a[2], a[3], b[2], b[3]) * 1000
                na, nb = snap(m, a[2], a[3]), snap(m, b[2], b[3])
                if not na or not nb or set(na) & set(nb):
                    failed += 1
                    continue
                limit = (straight * DETOUR_MAX + 1000) * SERVICE_COST
                nodes = path(m, na, nb, limit)
                if nodes:
                    real = sum(haversine(*coord[x], *coord[y]) for x, y in zip(nodes, nodes[1:])) * 1000
                    if real > straight * DETOUR_MAX + 1000:
                        nodes = None
                if not nodes:
                    failed += 1
                    continue
                pts = [(a[2], a[3])] + [coord[n] for n in nodes] + [(b[2], b[3])]
                shapes[f"{key[0]}-{key[1]}"] = encode_polyline(simplify(pts, SIMPLIFY_M))
    return shapes, f"{len(shapes)} hops on track, {failed} straight"


def water_barriers() -> dict:
    if not WATER.exists():
        return {"rv": [], "wc": [], "wb": []}
    els = json.loads(WATER.read_text(encoding="utf-8"))["elements"]
    coord = {e["id"]: (e["lat"], e["lon"]) for e in els if e["type"] == "node"}
    ways = [w for w in els if w["type"] == "way"]
    line = lambda w: [coord[n] for n in w["nodes"]]
    rv = [encode_polyline(simplify(line(w), RIVER_SIMPLIFY_M)) for w in ways if w["tags"]["kind"] == "river"]
    length: dict[str, float] = defaultdict(float)
    for w in ways:
        if w["tags"]["kind"] == "canal":
            p = line(w)
            length[w["tags"]["name"]] += sum(haversine(*a, *b) for a, b in zip(p, p[1:]))
    canals = [line(w) for w in ways if w["tags"]["kind"] == "canal" and w["tags"]["name"] not in CANAL_SKIP
              and "enclosure" not in w["tags"]["name"].lower() and length[w["tags"]["name"]] >= CANAL_MIN_KM]
    # canal segment grid (~1 km cells) to find bridge crossings
    grid: dict[tuple[int, int], list] = defaultdict(list)
    for p in canals:
        for a, b in zip(p, p[1:]):
            for i in range(int(min(a[0], b[0]) * 100), int(max(a[0], b[0]) * 100) + 1):
                for j in range(int(min(a[1], b[1]) * 100), int(max(a[1], b[1]) * 100) + 1):
                    grid[(i, j)].append((a, b))
    pts: list[tuple[float, float]] = []
    for w in ways:
        if w["tags"]["kind"] != "bridge":
            continue
        p = line(w)
        for a, b in zip(p, p[1:]):
            cand = set()
            for i in range(int(min(a[0], b[0]) * 100), int(max(a[0], b[0]) * 100) + 1):
                for j in range(int(min(a[1], b[1]) * 100), int(max(a[1], b[1]) * 100) + 1):
                    cand.update(grid.get((i, j), ()))
            for c, d in cand:
                x = seg_cross(a, b, c, d)
                if x and all(haversine(*x, *q) * 1000 > BRIDGE_MERGE_M for q in pts):
                    pts.append(x)
    wc = [encode_polyline(simplify(p, CANAL_SIMPLIFY_M)) for p in canals]
    return {"rv": rv, "wc": wc, "wb": [[round(a, 5), round(b, 5)] for a, b in pts]}


def seg_cross(a, b, c, d):
    """Intersection point of segments a-b and c-d (lat, lon pairs), or None."""
    rx, ry = b[1] - a[1], b[0] - a[0]
    sx, sy = d[1] - c[1], d[0] - c[0]
    den = rx * sy - ry * sx
    if den == 0:
        return None
    t = ((c[1] - a[1]) * sy - (c[0] - a[0]) * sx) / den
    u = ((c[1] - a[1]) * ry - (c[0] - a[0]) * rx) / den
    if 0 <= t <= 1 and 0 <= u <= 1:
        return (a[0] + t * ry, a[1] + t * rx)
    return None


def simplify(pts: list[tuple[float, float]], tol_m: float) -> list[tuple[float, float]]:
    """Douglas-Peucker in a local metric projection."""
    from math import cos, radians
    if len(pts) < 3:
        return pts
    k = cos(radians(pts[0][0]))
    xy = [(lo * 111320 * k, la * 110540) for la, lo in pts]
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        s0, e0 = stack.pop()
        (x1, y1), (x2, y2) = xy[s0], xy[e0]
        dx, dy = x2 - x1, y2 - y1
        L2 = dx * dx + dy * dy
        best, bi = -1.0, -1
        for i in range(s0 + 1, e0):
            px, py = xy[i]
            if L2 == 0:
                d = ((px - x1) ** 2 + (py - y1) ** 2) ** 0.5
            else:
                t = max(0.0, min(1.0, ((px - x1) * dx + (py - y1) * dy) / L2))
                d = ((px - x1 - t * dx) ** 2 + (py - y1 - t * dy) ** 2) ** 0.5
            if d > best:
                best, bi = d, i
        if best > tol_m:
            keep[bi] = True
            stack += [(s0, bi), (bi, e0)]
    return [p for p, k2 in zip(pts, keep) if k2]


def encode_polyline(pts: list[tuple[float, float]]) -> str:
    out = []
    plat = plon = 0
    for lat, lon in pts:
        ilat, ilon = round(lat * 1e5), round(lon * 1e5)
        for v in (ilat - plat, ilon - plon):
            v = ~(v << 1) if v < 0 else v << 1
            while v >= 0x20:
                out.append(chr((0x20 | (v & 0x1F)) + 63))
                v >>= 5
            out.append(chr(v + 63))
        plat, plon = ilat, ilon
    return "".join(out)


def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    from math import asin, cos, radians, sin, sqrt
    dlat, dlon = radians(lat2 - lat1), radians(lon2 - lon1)
    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
    return 2 * 6371 * asin(sqrt(a))


# ---------- place search index (docs/data/places.json) ----------
PLACES_OUT = ROOT / "docs" / "data" / "places.json"
PLACES_RAW = ROOT / "sources" / "raw" / "osm_places_index.json"   # scripts/osm_pbf_extract.py --places
GAZETTEER = ROOT / "sources" / "raw" / "bus" / "osm_gazetteer.json"  # fallback when PLACES_RAW is missing
WIKIDATA = ROOT / "sources" / "raw" / "bus" / "wikidata_places.json"
GEONAMES = ROOT / "sources" / "raw" / "bus" / "geonames_IN.txt"
CORE_BBOX = (22.3, 88.0, 23.1, 88.7)  # S, W, N, E: everything named is kept in here
PLACE_MAX_STOP_KM = 4.0                # outside CORE_BBOX: only places this close to a mapped stop
PLACE_TYPES = ["Area", "Town", "Village", "Block", "Airport", "Hospital", "Clinic", "University", "College", "School",
               "Temple", "Mosque", "Church", "Gurdwara", "Place of worship", "Park", "Mall", "Market", "Stadium",
               "Landmark", "Museum", "Cinema", "Office", "IT park", "Housing", "Building", "Station", "Bus stop",
               "Street", "Crossing", "Hotel", "Restaurant", "Police station", "Post office", "Government office",
               "Ghat", "Lake", "Bridge", "Place", "Cemetery", "Bus terminus"]
T = {t: i for i, t in enumerate(PLACE_TYPES)}
LOCALITY_TYPES = {"Area", "Town", "Village", "Block"}
ACRONYM_TYPES = {"University", "College", "Hospital", "Landmark", "Museum", "Stadium", "IT park", "Government office", "Airport"}
RELIGION_TYPE = {"hindu": "Temple", "jain": "Temple", "buddhist": "Temple", "muslim": "Mosque", "christian": "Church", "sikh": "Gurdwara"}
IT_PARK = re.compile(r"\b(tech ?park|it park|infospace|infinity|techpolis|tech ?city|software|ecospace|eco space|"
                     r"bengal intelligent|dlf|candor|unitech|webel|tcs|wipro|infosys|cognizant|accenture|ibm|godrej waterside)\b", re.I)
ROMAN = re.compile(r"\b(i{1,3}|iv|v|vi{0,3}|ix|x)\b", re.I)


STATION_SUFFIX = re.compile(r"\s+(railway station|metro station|station|rail station|junction railway station)$", re.I)


def norm_key(s: str) -> str:
    """Same idea as normName in docs/app.js: spelling-tolerant key for dedupe."""
    s = STATION_SUFFIX.sub("", s.lower())
    s = re.sub(r"[^a-z0-9]", "", s)
    s = re.sub(r"([bcdgkpst])h", r"\1", s).replace("v", "b").replace("w", "b").replace("f", "p")
    s = s.replace("ee", "i").replace("oo", "u").replace("a", "o")
    return re.sub(r"(.)\1+", r"\1", s)


def classify(kind: str, ex: dict, name: str) -> tuple[str, int] | None:
    """(type label, rank 0..9) for an OSM row, or None to leave it out."""
    k, _, v = kind.partition("=")
    span = ex.get("span", 0)
    if k == "place":
        return {"city": ("Town", 9), "town": ("Town", 9), "suburb": ("Area", 8), "quarter": ("Area", 7),
                "neighbourhood": ("Area", 7), "city_block": ("Block", 6), "village": ("Village", 5),
                "hamlet": ("Village", 3), "locality": ("Area", 4), "isolated_dwelling": ("Place", 2),
                "square": ("Landmark", 5), "island": ("Place", 4)}.get(v)
    if k == "highway":
        if v == "bus_stop":
            return ("Bus stop", 3)
        L = ex.get("len", 0)
        base = {"motorway": 6, "trunk": 6, "primary": 6, "secondary": 5, "tertiary": 4}.get(v, 3)
        return ("Bridge", 6) if re.search(r"\b(setu|bridge)\b", name, re.I) else ("Street", base + (L > 2000))
    if kind == "junction=yes":
        return ("Crossing", 6)
    if k == "aeroway":
        return ("Airport", 9) if v == "aerodrome" else None
    if k in ("railway", "public_transport"):
        if v in ("station", "halt"):
            return ("Station", 5)
        if v in ("stop", "platform", "tram_stop", "stop_position"):
            return ("Bus stop", 2)
        return None  # subway entrances, crossings
    if k == "amenity" or k == "healthcare":
        if v in ("hospital",):
            return ("Hospital", 7 if span > 80 or k == "amenity" else 6)
        if v in ("clinic", "centre", "nursing_home", "blood_bank", "laboratory", "sample_collection", "doctor"):
            return ("Clinic", 3)
        if v == "university":
            return ("University", 7)
        if v == "college":
            return ("College", 6)
        if v in ("school", "kindergarten"):
            return ("School", 4 if span > 60 else 3)
        if v == "place_of_worship":
            return (RELIGION_TYPE.get(ex.get("religion", ""), "Place of worship"), 6 if span > 100 else 4)
        if v == "marketplace":
            return ("Market", 6)
        if v in ("cinema", "theatre", "arts_centre"):
            return ("Cinema" if v == "cinema" else "Landmark", 5)
        if v in ("conference_centre", "exhibition_centre", "events_venue", "community_centre", "library"):
            return ("Landmark", 5 if span > 100 else 4)
        if v == "police":
            return ("Police station", 4)
        if v == "post_office":
            return ("Post office", 3)
        if v in ("townhall", "courthouse", "public_building"):
            return ("Government office", 5)
        if v == "bus_station":
            return ("Bus terminus", 5)
        if v == "ferry_terminal":
            return ("Ghat", 5)
        if v == "restaurant":
            return ("Restaurant", 2)
        if v in ("bank",):
            return ("Office", 2)
        if v in ("grave_yard", "crematorium"):
            return ("Cemetery", 4)
        if v in ("ticket_validator", "bench", "shelter"):
            return None
        return ("Landmark", 3)
    if k == "shop":
        return ("Mall", 7) if v in ("mall", "department_store") else ("Market", 4)
    if k == "tourism":
        if v in ("attraction", "zoo", "theme_park", "viewpoint"):
            return ("Landmark", 7)
        if v in ("museum", "gallery"):
            return ("Museum", 7)
        if v in ("hotel", "hostel", "guest_house", "motel"):
            return ("Hotel", 2)
        if v == "apartment":
            return ("Housing", 3)
        if v in ("artwork", "information", "picnic_site", "camp_site"):
            return None
        return ("Landmark", 3)
    if k == "leisure":
        if v in ("stadium", "sports_centre") and span > 80:
            return ("Stadium", 7 if v == "stadium" else 5)
        if v in ("park", "garden", "nature_reserve", "water_park", "golf_course"):
            return ("Park", 6 if span > 400 else 4 if span > 100 else 3)
        if v in ("playground", "pitch", "fitness_centre", "swimming_pool", "track", "fitness_station"):
            return ("Park", 2) if span > 100 else None
        return ("Landmark", 3)
    if k == "historic":
        return ("Landmark", 6 if span > 50 else 4) if v not in ("city_gate", "milestone", "boundary_stone") else None
    if k == "office":
        return ("IT park", 6) if IT_PARK.search(name) else ("Government office" if v == "government" else "Office", 4 if span > 60 else 3)
    if k == "landuse":
        if v == "residential":
            return ("Housing", 4)
        if v in ("retail",):
            return ("Market", 5)
        if v in ("commercial",):
            return ("IT park", 6) if IT_PARK.search(name) else ("Office", 4)
        if v == "religious":
            return ("Temple", 5)
        if v == "cemetery":
            return ("Cemetery", 4)
        if v in ("recreation_ground", "village_green"):
            return ("Park", 4)
        if v in ("industrial", "railway", "military"):
            return ("Landmark", 3)
        return None
    if k == "building":
        if v in ("apartments", "residential", "house", "dormitory"):
            return ("Housing", 3 if span > 40 else 2)
        if v in ("hospital",):
            return ("Hospital", 5)
        if v in ("school",):
            return ("School", 3)
        if v in ("college", "university"):
            return ("College", 5)
        if v in ("temple", "mosque", "church", "religious", "chapel", "shrine"):
            return ({"mosque": "Mosque", "church": "Church", "chapel": "Church"}.get(v, "Temple"), 4)
        if v in ("commercial", "office", "retail"):
            return ("IT park", 6) if IT_PARK.search(name) else ("Office", 3)
        if v in ("train_station", "transportation"):
            return None
        return ("Building", 3 if span > 40 else 2)
    if k == "man_made":
        return ("Bridge", 5) if v == "bridge" and span > 100 else None
    if k == "bridge":
        return ("Bridge", 5)
    if k == "natural":
        return ("Lake", 4) if v in ("water",) else None
    return None


GN_CODES = {"PPL": ("Area", 6), "PPLX": ("Area", 7), "PPLA": ("Town", 9), "PPLA2": ("Town", 8), "PPLA3": ("Town", 8),
            "PPLL": ("Village", 4), "UNIV": ("University", 7), "AIRP": ("Airport", 9), "SHRN": ("Temple", 6),
            "TMPL": ("Temple", 6), "CH": ("Church", 5), "MSQE": ("Mosque", 5), "GHAT": ("Ghat", 5),
            "HSP": ("Hospital", 6), "SCH": ("School", 4), "MALL": ("Mall", 7), "MKT": ("Market", 6), "PRK": ("Park", 5),
            "BLDG": ("Building", 3), "STDM": ("Stadium", 7), "MUS": ("Museum", 7), "FT": ("Landmark", 5),
            "CMTY": ("Cemetery", 4), "MNMT": ("Landmark", 6), "BDG": ("Bridge", 6)}
WD_TYPE = [(re.compile(r"\b(ssk|msk|f\.? ?p\.?|primary|school|vidyalaya|vidyapith|sishu|shishu|high sc|sc$|madrasah|academy)\b|school$", re.I), "School", 2),
           (re.compile(r"\b(hospital|sub-?centre|health|phc|clinic|nursing)\b", re.I), "Clinic", 3),
           (re.compile(r"\b(hotel|oyo|lodge|guest ?house|resort)\b", re.I), "Hotel", 1),
           (re.compile(r"\b(college|mahavidyalaya|institute)\b", re.I), "College", 5),
           (re.compile(r"\buniversity\b", re.I), "University", 7),
           (re.compile(r"\b(temple|mandir|kali|math|masjid|mosque|church|cathedral)\b", re.I), "Temple", 5),
           (re.compile(r"\b(park|garden|udyan)\b", re.I), "Park", 4),
           (re.compile(r"\b(station|halt)\b", re.I), "Station", 4),
           (re.compile(r"\b(kmcp|road|lane|sarani|street|avenue)\b", re.I), None, 0)]


def build_places() -> None:
    from math import cos, radians
    net = json.loads(OUT.read_text(encoding="utf-8"))
    stops = net["stops"]
    # stop grid (~1.1 km cells) for distance to the nearest stop and for dedupe against stop names
    sgrid: dict[tuple[int, int], list] = defaultdict(list)
    for s in stops:
        sgrid[(int(s[2] * 100), int(s[3] * 100))].append(s)

    def near_stop_km(lat: float, lon: float, r_cells: int = 4) -> float:
        ci, cj = int(lat * 100), int(lon * 100)
        best = 99.0
        for i in range(ci - r_cells, ci + r_cells + 1):
            for j in range(cj - r_cells, cj + r_cells + 1):
                for s in sgrid.get((i, j), ()):
                    best = min(best, haversine(lat, lon, s[2], s[3]))
        return best

    stop_norm: dict[str, list] = defaultdict(list)
    for s in stops:
        stop_norm[norm_key(s[1])].append((s[2], s[3]))
    S, W, N, E = CORE_BBOX
    in_core = lambda la, lo: S <= la <= N and W <= lo <= E

    def keep_region(la: float, lo: float) -> bool:
        return in_core(la, lo) or near_stop_km(la, lo) <= PLACE_MAX_STOP_KM

    cands: list[dict] = []  # {name, alts, lat, lon, type, rank, src}
    stats = Counter()

    def add(name: str, alts: list[str], la: float, lo: float, typ: str, rank: int, src: str) -> None:
        name = " ".join(name.split())
        if len(name) < 2 or not re.search(r"[A-Za-z]", name):
            return
        if not keep_region(la, lo):
            stats["outside_region"] += 1
            return
        alts = [a for a in dict.fromkeys(" ".join(x.split()) for x in alts) if a and a.lower() != name.lower() and re.search(r"[A-Za-z]", a)]
        cands.append({"name": name, "alts": alts, "lat": la, "lon": lo, "type": typ, "rank": rank, "src": src})
        stats[src] += 1

    # OpenStreetMap
    if PLACES_RAW.exists():
        rows = json.loads(PLACES_RAW.read_text(encoding="utf-8"))["rows"]
    else:  # older gazetteer: same row shape minus the extras
        rows = [[r[0], r[1], r[3], r[4], {}] for r in json.loads(GAZETTEER.read_text(encoding="utf-8"))["elements"]]
    for la, lo, kind, nm, ex in rows:
        en = nm.get("name:en") or nm.get("int_name")
        base = nm.get("name", "")
        name = base if re.search(r"[A-Za-z]", base) else (en or "")
        if not name:
            continue
        c = classify(kind, ex, name)
        if not c:
            continue
        alts = [nm[k] for k in ("name:en", "alt_name", "alt_name:en", "old_name", "old_name:en", "official_name",
                                "official_name:en", "short_name", "loc_name", "int_name") if k in nm]
        alts = [a for x in alts for a in x.split(";")]
        add(name, alts, la, lo, c[0], c[1], "osm")
    # GeoNames (CC BY 4.0)
    S2, W2, N2, E2 = 21.5, 87.4, 23.6, 89.1
    with GEONAMES.open(encoding="utf-8") as f:
        for line in f:
            p = line.rstrip("\n").split("\t")
            la, lo = float(p[4]), float(p[5])
            if not (S2 <= la <= N2 and W2 <= lo <= E2):
                continue
            c = GN_CODES.get(p[7])
            if not c:
                continue
            alts = [a for a in p[3].split(",") if a.isascii() and 2 < len(a) < 40][:6]
            add(p[2] or p[1], [p[1]] + alts, la, lo, c[0], c[1], "geonames")
    # Wikidata (CC0)
    wd = json.loads(WIKIDATA.read_text(encoding="utf-8"))
    for tile in wd["tiles"].values():
        for la, lo, _q, nm in tile:
            name = nm.get("en")
            if not name:
                continue
            typ, rank = "Place", 4
            for rx, t, r in WD_TYPE:
                if rx.search(name):
                    typ, rank = t, r
                    break
            notable = bool(nm.get("bn") or nm.get("alias"))
            # standalone Wikidata items are mostly census villages and school or hotel listings with clipped
            # names; keep only notable ones (a Bengali label or an alias), never schools, hotels, clinics or
            # stations (stations are transit stops already). They still lend aliases to OSM places (dedupe below).
            if typ is None or typ in ("School", "Hotel", "Clinic", "Station"):
                continue
            if not notable:
                continue
            add(name, nm.get("alias", [])[:6], la, lo, typ, rank + (1 if notable and typ == "Place" else 0), "wikidata")

    # dedupe: same spelling key (of the name or any alt name) close by. Localities and streets merge over DEDUPE_FAR_M, the rest over DEDUPE_M.
    DEDUPE_M, DEDUPE_FAR_M = 300, 1500
    cands.sort(key=lambda c: (-c["rank"], {"osm": 0, "geonames": 1, "wikidata": 2}[c["src"]]))
    kept: list[dict] = []
    by_key: dict[str, list[dict]] = defaultdict(list)
    for c in cands:
        keys = list(dict.fromkeys([norm_key(c["name"])] + [norm_key(a) for a in c["alts"]]))  # GeoNames Taliganja = Tollygunge
        far = c["type"] in LOCALITY_TYPES or c["type"] in ("Street", "Place", "Station")
        dup = None
        for k in keys:
            for o in by_key.get(k, ()):
                lim = DEDUPE_FAR_M if (far or o["type"] in LOCALITY_TYPES or o["type"] in ("Street", "Place")) else DEDUPE_M
                if haversine(c["lat"], c["lon"], o["lat"], o["lon"]) * 1000 <= lim:
                    dup = o
                    break
            if dup:
                break
        if dup:
            for a in [c["name"]] + c["alts"]:
                if a.lower() != dup["name"].lower() and a not in dup["alts"]:
                    dup["alts"].append(a)
            if c["src"] == "wikidata" and dup["src"] != "wikidata":
                dup["wd"] = True
            stats["merged"] += 1
            continue
        # a transit stop of the same name close by already covers it in the search
        nk = norm_key(c["name"])
        if any(haversine(c["lat"], c["lon"], a, b) * 1000 <= (1200 if far else 500) for a, b in stop_norm.get(nk, ())):
            stats["same_as_stop"] += 1
            continue
        kept.append(c)
        for k in keys:
            by_key[k].append(c)
    for c in kept:
        if c.pop("wd", False):
            c["rank"] = min(9, c["rank"] + 1)
        # acronym alias for long names: Indian Institute of Management Calcutta -> IIMC
        words = [w for w in re.split(r"[^A-Za-z]+", c["name"]) if w and w.lower() not in ("of", "and", "the", "for", "&")]
        if 3 <= len(words) <= 7 and c["type"] in ACRONYM_TYPES and c["rank"] >= 5:
            acr = "".join(w[0] for w in words).upper()
            if acr not in c["alts"]:
                c["alts"].append(acr)
        c["alts"] = [a for a in c["alts"] if norm_key(a) != norm_key(c["name"])][:5]

    # area hint: nearest suburb or town (OSM place=suburb, town, city) centre within AREA_HINT_KM
    AREA_HINT_KM = 3.0
    kept.sort(key=lambda c: (c["type"] not in LOCALITY_TYPES, -c["rank"], c["name"].lower()))
    locs = [(i, c) for i, c in enumerate(kept) if c["type"] in ("Area", "Town") and c["rank"] >= 8 and c["src"] == "osm"]  # suburbs and towns
    lgrid: dict[tuple[int, int], list] = defaultdict(list)
    for i, c in locs:
        lgrid[(int(c["lat"] * 50), int(c["lon"] * 50))].append(i)
    out_rows = []
    for idx, c in enumerate(kept):
        ci, cj = int(c["lat"] * 50), int(c["lon"] * 50)
        best, bi = AREA_HINT_KM, -1
        for i in range(ci - 2, ci + 3):
            for j in range(cj - 2, cj + 3):
                for li in lgrid.get((i, j), ()):
                    if li == idx or norm_key(kept[li]["name"]) in norm_key(c["name"]):
                        continue
                    d = haversine(c["lat"], c["lon"], kept[li]["lat"], kept[li]["lon"])
                    # a town only counts as the hint when no area of the town is close
                    d *= 1.6 if kept[li]["type"] == "Town" else 1.0
                    if d < best:
                        best, bi = d, li
        row = [c["name"], round(c["lat"], 5), round(c["lon"], 5), T[c["type"]], c["rank"], bi]
        if c["alts"]:
            row.append("|".join(c["alts"]))
        out_rows.append(row)
    doc = {
        "meta": {
            "built": date.today().isoformat(),
            "licence": "ODbL 1.0: (c) OpenStreetMap contributors; GeoNames (geonames.org) CC BY 4.0; Wikidata CC0",
            "fields": ["name", "lat", "lon", "type index", "rank 0-9 (higher first)", "area hint row index or -1", "alt names joined by | (optional)"],
            "types": PLACE_TYPES,
        },
        "p": out_rows,
    }
    PLACES_OUT.write_text(json.dumps(doc, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    import gzip
    raw = PLACES_OUT.read_bytes()
    by_type = Counter(PLACE_TYPES[r[3]] for r in out_rows)
    print(f"wrote {PLACES_OUT.relative_to(ROOT)}: {len(raw) / 1024:.1f} KiB raw, {len(gzip.compress(raw, 9)) / 1024:.1f} KiB gzip, "
          f"{len(out_rows)} places; sources {dict(stats)}; by type {dict(by_type.most_common())}")


if __name__ == "__main__":
    import sys
    if "--places" not in sys.argv:
        main()
    build_places()
