"""Build docs/data/network.json, the compact network used by the static trip planner in docs/.

Inputs (read only): gtfs/{routes,trips,stops,stop_times,transfers}.txt (generated by build_gtfs.py, so only
located stops and estimated or sourced stop times), data/{mode}/routes.csv for headways, and
data/rail/{route_stops,timetable}.csv for rail stop patterns and real run times.
Output: docs/data/network.json (minified, coordinates rounded to 5 decimals). Prints its size.

Modelling:
- Non-rail routes: one stop pattern per direction from the GTFS template trip (service "daily", else
  "weekdays", else the first one), cumulative ride minutes from its stop times.
- Rail: the main pattern per direction is data/rail/route_stops.csv (longest trip pattern, located stops
  only). Each hop's run time is the median over all timetable trips that call at both stops consecutively
  along that pattern. Trips calling at stations outside the main pattern (branches, through workings) add
  up to MAX_RAIL_VARIANTS extra patterns per direction, timed from their median trip.
- Headway: mean of headway_min_peak and headway_min_offpeak in data/{mode}/routes.csv. Blank for bus,
  minibus, auto: the build_gtfs defaults (15, 15, 10). Blank for rail: service span / trip count.
- Never emits interpolated coordinates: every stop is a located GTFS stop.

Usage: venv/bin/python scripts/build_web.py
"""
from __future__ import annotations

import csv
import json
import statistics
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GTFS = ROOT / "gtfs"
DATA = ROOT / "data"
OUT = ROOT / "docs" / "data" / "network.json"

MODE_COLOR = {
    "bus": "#E8590C",
    "minibus": "#B7791F",
    "metro": "#7B2CBF",
    "rail": "#1C7ED6",
    "auto": "#2B8A3E",
    "ferry": "#0B7285",
    "tram": "#C2255C",
}
DEFAULT_HEADWAY = {"bus": 15, "minibus": 15, "auto": 10}
MAX_RAIL_VARIANTS = 3
MODE_DIRS = ["bus", "metro", "rail", "auto", "ferry", "tram"]


def read(path: Path) -> list[dict]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def hms_to_min(t: str) -> float:
    h, m, s = (int(x) for x in t.split(":"))
    return h * 60 + m + s / 60


def route_mode(r: dict) -> str:
    rt, ag = r["route_type"], r["agency_id"]
    if rt == "1":
        return "metro"
    if rt == "2":
        return "rail"
    if rt == "0":
        return "tram"
    if rt == "4":
        return "ferry"
    if ag == "share_auto":
        return "auto"
    if ag == "minibus":
        return "minibus"
    return "bus"


def headways() -> dict[str, float | None]:
    out: dict[str, float | None] = {}
    for mode in MODE_DIRS:
        p = DATA / mode / "routes.csv"
        if not p.exists():
            continue
        for r in read(p):
            vals = [float(v) for v in (r["headway_min_peak"], r["headway_min_offpeak"]) if v.strip()]
            out[r["route_id"]] = round(sum(vals) / len(vals), 1) if vals else None
    return out


def main() -> None:
    stops_rows = read(GTFS / "stops.txt")
    stop_idx: dict[str, int] = {}
    stops: list[list] = []
    for s in stops_rows:
        stop_idx[s["stop_id"]] = len(stops)
        stops.append([s["stop_id"], s["stop_name"], round(float(s["stop_lat"]), 5), round(float(s["stop_lon"]), 5), []])

    routes_rows = read(GTFS / "routes.txt")
    hw = headways()
    trips = read(GTFS / "trips.txt")
    trips_by_rd: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for t in trips:
        trips_by_rd[(t["route_id"], t["direction_id"])].append(t)

    # stop_times only for non-rail template trips (rail comes from data/rail/timetable.csv)
    wanted: set[str] = set()
    chosen: dict[tuple[str, str], str] = {}
    for key, ts in trips_by_rd.items():
        if key[0].startswith("rail_"):
            continue
        pref = {"daily": 0, "weekdays": 1}
        t = sorted(ts, key=lambda x: pref.get(x["service_id"], 2))[0]
        chosen[key] = t["trip_id"]
        wanted.add(t["trip_id"])
    st_by_trip: dict[str, list[tuple[int, str, float]]] = defaultdict(list)
    with (GTFS / "stop_times.txt").open(newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            if r["trip_id"] in wanted:
                st_by_trip[r["trip_id"]].append((int(r["stop_sequence"]), r["stop_id"], hms_to_min(r["departure_time"])))

    # rail inputs
    rail_main: dict[tuple[str, str], list[str]] = defaultdict(list)
    for r in sorted(read(DATA / "rail" / "route_stops.csv"), key=lambda x: (x["route_id"], x["direction"], int(x["seq"]))):
        if r["stop_id"] in stop_idx:
            rail_main[(r["route_id"], r["direction"])].append(r["stop_id"])
    rail_trips: dict[tuple[str, str, str], list[tuple[int, str, float]]] = defaultdict(list)
    for r in read(DATA / "rail" / "timetable.csv"):
        t = r["departure"] or r["arrival"]
        if not t:
            continue
        rail_trips[(r["route_id"], r["direction"], r["trip_id"])].append((int(r["seq"]), r["stop_id"], hms_to_min(t)))
    rail_by_rd: dict[tuple[str, str], list[list[tuple[str, float]]]] = defaultdict(list)
    for (rid, d, _tid), rows in rail_trips.items():
        rows.sort()
        seq: list[tuple[str, float]] = []
        prev = None
        off = 0.0
        for _, sid, m in rows:
            if prev is not None and m + off < prev - 1:
                off += 1440  # past midnight
            m += off
            prev = m
            if sid in stop_idx:
                seq.append((sid, m))
        if len(seq) >= 2:
            rail_by_rd[(rid, d)].append(seq)

    out_routes = []
    n_variants = 0
    for r in routes_rows:
        rid = r["route_id"]
        mode = route_mode(r)
        h = hw.get(rid)
        if h is None:
            h = DEFAULT_HEADWAY.get(mode)
        patterns = []  # list of (direction, [stop idx], [cum min], headway or None)
        dirs = sorted({k[1] for k in trips_by_rd if k[0] == rid})
        for d in dirs:
            if mode != "rail":
                rows = sorted(st_by_trip.get(chosen.get((rid, d), ""), []))
                if len(rows) < 2:
                    continue
                t0 = rows[0][2]
                patterns.append((d, [stop_idx[s] for _, s, _ in rows], [round(m - t0, 1) for _, _, m in rows], None))
                continue
            trips_rd = rail_by_rd.get((rid, d), [])
            main_pat = rail_main.get((rid, d), [])
            main_set = set(main_pat)
            if len(main_pat) >= 2:
                hop_times: list[list[float]] = [[] for _ in range(len(main_pat) - 1)]
                pos = {s: i for i, s in enumerate(main_pat)}
                for seq in trips_rd:
                    for (a, ta), (b, tb) in zip(seq, seq[1:]):
                        if a in pos and b in pos and pos[b] == pos[a] + 1 and tb >= ta:
                            hop_times[pos[a]].append(tb - ta)
                cum = [0.0]
                for i, ht in enumerate(hop_times):
                    if ht:
                        step = statistics.median(ht)
                    else:  # no trip calls at both: use any trip calling at both, else 40 km/h straight line x 1.2
                        a, b = main_pat[i], main_pat[i + 1]
                        spans = [dict(seq)[b] - dict(seq)[a] for seq in trips_rd if a in dict(seq) and b in dict(seq) and dict(seq)[b] > dict(seq)[a]]
                        if spans:
                            step = statistics.median(spans)
                        else:
                            sa, sb = stops[stop_idx[a]], stops[stop_idx[b]]
                            step = haversine(sa[2], sa[3], sb[2], sb[3]) * 1.2 / 40 * 60
                    cum.append(cum[-1] + max(step, 0.5))
                patterns.append((d, [stop_idx[s] for s in main_pat], [round(c, 1) for c in cum], None))
            # branch and through patterns not covered by the main pattern
            pat_count: Counter = Counter()
            pat_trips: dict[tuple, list] = defaultdict(list)
            for seq in trips_rd:
                key = tuple(s for s, _ in seq)
                if set(key) - main_set:
                    pat_count[key] += 1
                    pat_trips[key].append(seq)
            seen_sets: list[set] = []
            for key, cnt in pat_count.most_common():
                if len([p for p in patterns if p[0] == d]) > MAX_RAIL_VARIANTS:
                    break
                ks = set(key)
                if any(ks <= s for s in seen_sets):
                    continue
                seen_sets.append(ks)
                seqs = sorted(pat_trips[key], key=lambda q: q[-1][1] - q[0][1])
                med = seqs[len(seqs) // 2]
                t0 = med[0][1]
                deps = sorted(q[0][1] for q in pat_trips[key])
                vh = round(max(30.0, (deps[-1] - deps[0]) / cnt), 0) if cnt > 1 else 240.0
                patterns.append((d, [stop_idx[s] for s, _ in med], [round(m - t0, 1) for _, m in med], min(vh, 240.0)))
                n_variants += 1
            if mode == "rail" and h is None and trips_rd:
                deps = sorted(q[0][1] for q in trips_rd)
                h = round(max(20.0, (deps[-1] - deps[0]) / len(trips_rd)), 0)
        if not patterns:
            continue
        for _, sidx, _, _ in patterns:
            for i in sidx:
                if mode not in stops[i][4]:
                    stops[i][4].append(mode)
        entry = {
            "id": rid,
            "s": r["route_short_name"],
            "l": r["route_long_name"],
            "m": mode,
            "a": r["agency_id"],
            "c": MODE_COLOR[mode],
            "h": h if h is not None else 30,
            "p": [[int(d), sidx, cum] + ([vh] if vh is not None else []) for d, sidx, cum, vh in patterns],
        }
        if r.get("route_color"):
            entry["lc"] = "#" + r["route_color"]
        out_routes.append(entry)

    # keep only stops used by a pattern, then remap indices
    used = sorted({i for rt in out_routes for p in rt["p"] for i in p[1]})
    remap = {old: new for new, old in enumerate(used)}
    out_stops = [stops[i] for i in used]
    for rt in out_routes:
        for p in rt["p"]:
            p[1] = [remap[i] for i in p[1]]
    for s in out_stops:
        s[4] = "".join(sorted({m[0] if m != "minibus" else "n" for m in s[4]}))  # b bus, n minibus, m metro, r rail, a auto, f ferry, t tram
    id_to_new = {s[0]: i for i, s in enumerate(out_stops)}
    transfers = []
    for t in read(GTFS / "transfers.txt"):
        a, b = id_to_new.get(t["from_stop_id"]), id_to_new.get(t["to_stop_id"])
        if a is not None and b is not None and t.get("min_transfer_time"):
            transfers.append([a, b, round(int(t["min_transfer_time"]) / 60, 1)])

    net = {
        "meta": {
            "built": date.today().isoformat(),
            "source": "https://github.com/arkodeepg/calcutta-transport",
            "licence": "ODbL 1.0, (c) OpenStreetMap contributors and the sources in CREDITS.md",
            "stop_fields": ["id", "name", "lat", "lon", "modes"],
            "mode_letters": {"b": "bus", "n": "minibus", "m": "metro", "r": "rail", "a": "auto", "f": "ferry", "t": "tram"},
            "pattern_fields": ["direction", "stop_indices", "cumulative_ride_min", "headway_override_min (optional)"],
            "colors": MODE_COLOR,
        },
        "stops": out_stops,
        "routes": out_routes,
        "transfers": transfers,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(net, separators=(",", ":"), ensure_ascii=False), encoding="utf-8")
    by_mode = Counter(r["m"] for r in out_routes)
    print(f"wrote {OUT.relative_to(ROOT)}: {OUT.stat().st_size / 1024:.1f} KiB, {len(out_stops)} stops, "
          f"{len(out_routes)} routes ({dict(by_mode)}), {sum(len(r['p']) for r in out_routes)} patterns "
          f"(rail variants {n_variants}), {len(transfers)} transfers")


def haversine(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    from math import asin, cos, radians, sin, sqrt
    dlat, dlon = radians(lat2 - lat1), radians(lon2 - lon1)
    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
    return 2 * 6371 * asin(sqrt(a))


if __name__ == "__main__":
    main()
